export type {QueryFetcher, QueryArgs, QueryScalarType, QueryFlatType} from './QueryFetcher';
export {query$} from './QueryFetcher';
export type {BookStoreFetcher, BookStoreArgs, BookStoreScalarType, BookStoreFlatType} from './BookStoreFetcher';
export {bookStore$, bookStore$$} from './BookStoreFetcher';
export type {AnyFetcher} from './AnyFetcher';
export {any$, any$$} from './AnyFetcher';
export type {BookFetcher, BookArgs, BookScalarType, BookFlatType} from './BookFetcher';
export {book$, book$$} from './BookFetcher';
export type {AuthorFetcher, AuthorArgs, AuthorScalarType, AuthorFlatType} from './AuthorFetcher';
export {author$, author$$} from './AuthorFetcher';
export type {BookConnectionFetcher} from './BookConnectionFetcher';
export {bookConnection$, bookConnection$$} from './BookConnectionFetcher';
export type {BookEdgeFetcher} from './BookEdgeFetcher';
export {bookEdge$, bookEdge$$} from './BookEdgeFetcher';
export type {PageInfoFetcher} from './PageInfoFetcher';
export {pageInfo$, pageInfo$$} from './PageInfoFetcher';
export type {AuthorConnectionFetcher} from './AuthorConnectionFetcher';
export {authorConnection$, authorConnection$$} from './AuthorConnectionFetcher';
export type {AuthorEdgeFetcher} from './AuthorEdgeFetcher';
export {authorEdge$, authorEdge$$} from './AuthorEdgeFetcher';
export type {MutationFetcher, MutationArgs} from './MutationFetcher';
export {mutation$} from './MutationFetcher';
